# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  # Matches the docker container name for postgres
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aws_ec2_docker_rails_app_development

test:
  <<: *default
  database: aws_ec2_docker_rails_app_test

production:
  <<: *default
  database: aws_ec2_docker_rails_app_production
